language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: lzjUaCHcxQUS7OWy8BJs+V38LkUpIlutODI8YmBEMsbXAisJryofqQ/UbvrikEcAetzuaa3QtUQhVSB2FNxuuTFYGhkDoPTbMaWq8ZFv7Ck3bMy8lvqNAbqSzTkPJlikxkFolkSgIxXNpusrQGnS5y/mEDcobMUxBMb8ZiEaoM4tpOsTuNNIy+LOXoLpjs/Q/qdH3ixC/w1d4QxtED+4QrVgP43wmxYmC4QbRXddjd7jui1q7SkY5cgzTNY+qTaa62U/T3eP0e47OpIw7q21lj38UrbO35dQTFe12Zovo8f0mdqEChZ7LMc4J74ryO1H4g8Gexyzcy4o9EijKh7/2+LSYhF+tekaabgp1DHh2mtTKMbmHHXA7wshPsxl/kIoE1naGCdyipCfLYTc6Y7XxmFAxM9122Qt76guluwSWPeGkxtTCQ2W6iGTqqkvVIP92gWHBA7aSWAw0mbgxLC43kpBsGa8bXR+S5rFcDByvCSCM2ehV0N5Xp/+E6OIg2Rz4rAD1X768lcnFZTC7reOCx1Y9AiA/XusbFZShKpCqaLkR6x/4Sd4SNFpccdI8o5M/xFe8YcnNpb0SufBCtXaZFztxFVDg25qnci/d2KI65lZ2fBuveS5z0CBNdo/efOF+y0rgAaJ5DAtU+OMLbBmbl8CxRDgzVLNMtRn66XEgwI=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
