language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: eQUHN5vDMM1CzCH7k0w/eyC8h1mteCaeGnNw4QEi8YVAMnJ3D7AYCUNbj9pZyeYH8JmiwM9DMCmlc/1bwsCyMZjWqWMUFmQW+gOthBM9Ywtgg1fjLO3TODCduGeQ9TFAOOjhUyyCq7QNH5Xbd3WVOKJClE7z3k+HKqW14hGqb5cb9CzTyT9LIZ+JI2mbgyftPEIeTgb6ruXbpu+p/eEQXKRfDFOBP6GlfGX4PjFe6vOfe0my3xpC4qqowId3MRHjwyJdY3WtEjR69Oki+U3+a2XYAcMZXuB9tXkUFrtuigHZ7+agW6P8Do0HJxumRtawR2FOZFr4xAFra6sDsSlHMstqobqbI8KQUq5CSaVKOPwEqcyG+XPqi1Cwi1cOaa3RGxKqzTcERMJ6aeI/9cxy/qsif8HqpvbJGRjUZb00Izk8805KvedY0SsLkiEVxqy+30ID7FIMrneA8H3FcIkxVGFZt+ixioIuKrdhIJtgHx0x9xTlfXLEgSW8mq0Y5ClIH/Nxehs00LCcTs25srkEE0OIGp6Yhl4YZv2Dmk+oO1obAQtMTPmGhyFgPwkS2Ru3AnPSD3I+xFk/K7A/0SrkwKsZQN+TII0w3W3T2FNS4WtxupmmOobY2lUAl6k4DK57Rgshr5tSD/ae+J9b+O1jFTF01Yf2+DznFsFBHNoH6wk=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
